version: '3.8'

services:
  react-app:
    image: front-chat-aegea
    container_name: react-app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.react-app.entrypoints=web"
      - "traefik.http.services.react-app.loadbalancer.server.port=80"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true